version: "3.8"

services:
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./.env:/app/.env
    depends_on:
      - redis

  message-service:
    build:
      context: ./services/message-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./.env:/app/.env
    depends_on:
      - redis

  image-service:
    build:
      context: ./services/image-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - ./images:/app/images
      - ./.env:/app/.env
    depends_on:
      - redis

  configs-service:
    build:
      context: ./services/configs-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    volumes:
      - ./.env:/app/.env
    depends_on:
      - redis

  model-service:
    build:
      context: ./services/model-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    volumes:
      - ./.env:/app/.env
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
